### ISSUE TITLE
No executable file found

### ISSUE THREAD

**Issue by thecowmilk** [jklmnn/imagejs#10]
So I just cloned this repo on my kali linux and when I switched to imagejs folder, there was no executable file and commands found in README.md didn't worked.

I hope this is will be fixed soon. Thank is advance.

**Comment by jklmnn** [comment]
Which commands did you run and have you installed `cmake` and `build-essential`?

**Comment by thecowmilk** [comment]
Hello, thanks for the help. I actually didn't had "cmake" :). I'm closing this thread.
