### ISSUE TITLE
Uncaught syntaxError: Illegal character

### ISSUE THREAD

**Issue by Suba-Sah** [jklmnn/imagejs#11]
After injecting code into the image and then I load into the script tag to run the Javascript but all the time it throws the same error:  UNCAUGHT SYNTAXERROR: ILLEGAL CHARACTER.

**Comment by jklmnn** [comment]
Did you test the code before injecting it? Also what image type did you use?
I definitely need to know the command you used to debug this. In the best case you also can give me a code example that triggers this error.

**Comment by Suba-Sah** [comment]
JS I am using is a really simple one just for testing with a gif image.

JS(**image.js**): `windows.alert("Here we go");`
And the command used is: `./imagejs gif image.js -i my_image.gif`
The HTML file has the following piece of code:
`<html>
      <head></head>
<body>
      <img src = "image.js.gif">
      <script src = "image.js.gif"></script>
</body>
</html>
`
I actually was following one video on youtube: [Video](https://www.youtube.com/watch?v=memPcI94YGA)

**Comment by Suba-Sah** [comment]
Hi @jklmnn ; if you noticed any issue with this approach then please let me know that could be really helpful to me.

**Comment by jklmnn** [comment]
Please excuse the long delay, I'm short on time currently. I'll try to fix this soon.

**Comment by jklmnn** [comment]
The problem was a closing comment `*/` that randomly appeared in the image data leading the parser parsing the image data. I fixed it in the latest commit. Please check if that fixed it for you.
