### ISSUE TITLE
please mention how to run this software in terminal in kali 2018

### ISSUE THREAD

**Issue by robinjoseph99** [jklmnn/imagejs#9]
after running git clone "https://github.com/jklmnn/imagejs" in terminal in kali linux 2018 the program is downloaded but there is problem in running the program as per your video in youtube i cant run it in terminal . please mention in the site about runing the program. 
imagejs is missing in the containning the video

**Comment by robinjoseph99** [comment]
imagejs is missing in the containning file

**Comment by jklmnn** [comment]
You have to compile it first. I have made the instructions in the readme a bit more clearly. Take a look at the build section. This should work without any problems on Kali and the resulting `imagejs` file should be in the build directory.

Beside that I have no idea what video you are talking about. I have never made any video and I am not responsible for anything done in videos created by third parties/other people.
